version: '3.2'
services:
  api:
    image: oidc-tutorial-api:latest
    container_name: oidc-tutorial-api
    volumes:
      - type: bind
        source: "${LOCAL_APP_DIR}"
        target: /opt/app
    env_file:
      - "${ENV_PATH}"
    network_mode: host
  nginx:
    image: oidc-tutorial-nginx:latest
    container_name: oidc-tutorial-nginx
    network_mode: host
  keycloak:
    image: oidc-tutorial-keycloak:latest
    container_name: oidc-tutorial-keycloak
    volumes:
      - type: bind
        source: ../keycloak-dist/export
        target: /opt/keycloak/data/import
    network_mode: host
    command: ["start-dev", "--http-port=8888", "--import-realm"]
